CREATE ROLE su_reg_user;
ALTER ROLE su_reg_user WITH SUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:Bmhbj7WsmzscPfSKS5fgPg==$nMijVQmb8CLvttajj3luhYs+GeT+dkk1fKCALAujZAk=:SLustM7lioeIJzQiKAJoUYJ1jAoLfzfFeYIKYLq0Q78=';
ALTER ROLE "su_reg_user" SET client_encoding TO 'UTF8';

